services:
  django-gunicorn:
    build: 
      context: .
    ports:
      - "8000:8000"
  
  nginx:
    build: 
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - django-gunicorn
    volumes:
      - ./RootToRoot/staticfiles:/staticfiles